// Domain types — storage-agnostic. Used by MemoryStore interface and all callers.
// Do NOT import from Prisma here — this file must work for both Postgres and SQLite.

export interface Topic {
  id: string
  name: string
  label: string
  category: string
  summary: string
  characterId: string | null  // null = shared across all characters
  createdAt: Date
  updatedAt: Date
}

export interface Session {
  id: string
  title: string
  createdAt: Date
}

export interface SessionSummary extends Session {
  messageCount: number
  previewMessages: string[]  // first few user message snippets
}

export interface Message {
  id: string
  role: string
  content: string
  personality: string
  sessionId: string
  createdAt: Date
}

// ── Spans ─────────────────────────────────────────────────────────────────────

export type SpanKind =
  | 'llm_call'
  | 'tool_use'
  | 'memory_read'
  | 'memory_write'
  | 'skill_match'
  | 'skill_fire'
  | 'apo_score'
  | 'sycophancy_detection'
  | 'user_correction'
  | 'mental_health_flag'
  | 'user_feedback'

export interface Span {
  id: string
  sessionId: string
  traceId: string
  kind: SpanKind
  status: 'ok' | 'error'
  durationMs: number | null
  metadata: Record<string, unknown> | null
  createdAt: Date
}

export interface SpanInput {
  sessionId: string
  traceId: string
  kind: SpanKind
  status?: 'ok' | 'error'
  durationMs?: number
  metadata?: Record<string, unknown>
}

// ── Skills ────────────────────────────────────────────────────────────────────

export interface SkillStat {
  id: string
  skillName: string
  characterId: string
  score: number
  trials: number
  lastFired: Date | null
  autoGenerated: boolean
  protected: boolean
  promoted: boolean
  staleAt: Date | null
  createdAt: Date
  updatedAt: Date
}

export interface SeedSkill {
  name: string
  description: string
  trigger: string
  body: string
  protected?: boolean
  autoGenerated?: boolean
}

// ── APO ───────────────────────────────────────────────────────────────────────

export type ApoSlot = 'character_personality' | 'skill_instructions' | 'tool_guidance'

export interface ApoVariant {
  id: string
  name: string
  slot: ApoSlot
  content: string
  score: number
  trials: number
  active: boolean
  parentId: string | null
  createdAt: Date
  updatedAt: Date
}

export interface SkillProposal {
  id: string
  skillName: string
  characterId: string
  oldBody: string
  newBody: string
  reason: string
  accepted: boolean | null  // null = pending, true = accepted, false = rejected
  autoAcceptAt: Date
  createdAt: Date
}

// ── Character Config ──────────────────────────────────────────────────────────

export type LlmProvider = 'openrouter' | 'gemini' | 'ollama'

export interface CharacterConfig {
  id: string
  name: string
  basePrompt: string
  avatarModel: string
  voiceLocal: string
  voiceCloud: string | null
  description: string
  provider: LlmProvider
  llmModel: string | null
  createdAt: Date
  updatedAt: Date
}

// ── Eviction ──────────────────────────────────────────────────────────────────

export interface StorageStats {
  topics: number
  sessions: number
  messages: number
  spans: number
  skills: number
  summaries: number
}

export interface EvictionOptions {
  maxSpanAgeDays?: number      // default: 30  — spans older than this are pruned
  maxSessionCount?: number     // default: 100 — keep only the N most recent sessions
  maxSummaryAgeDays?: number   // default: 90  — conversation summaries older than this are pruned
}

export interface EvictionResult {
  spansDeleted: number
  sessionsDeleted: number
  summariesDeleted: number
}

// ── Conversation Summaries ────────────────────────────────────────────────────

export interface ConversationSummaryRecord {
  id: string
  sessionId: string
  characterId: string
  summary: string
  turnStart: number
  turnEnd: number
  createdAt: Date
}
