"use client"

import { useState, useEffect } from "react"
import Header from "../components/Header"
import { personalities, defaultPersonality } from "../lib/personalities"
import { classifyTier, tierWarning } from "../lib/provider-tiers"

interface SkillStat {
  id: string
  skillName: string
  score: number
  trials: number
  promoted: boolean
  protected: boolean
  autoGenerated: boolean
  lastFired: string | null
}

interface SkillProposal {
  id: string
  skillName: string
  oldBody: string
  newBody: string
  reason: string
  autoAcceptAt: string
}

export default function Settings() {
  const [activePersonality, setActivePersonality] = useState(defaultPersonality)
  const [descriptions, setDescriptions] = useState<Record<string, string>>({})
  const [activeTab, setActiveTab] = useState<"personality" | "learned" | "grows" | "honesty" | "storage">("personality")
  const [skills, setSkills] = useState<SkillStat[]>([])
  const [skillsLoading, setSkillsLoading] = useState(false)
  const [resetConfirm, setResetConfirm] = useState<string | null>(null)
  const [proposals, setProposals] = useState<SkillProposal[]>([])
  const [proposalsLoading, setProposalsLoading] = useState(false)
  const [honestyStats, setHonestyStats] = useState<{
    sessionCount: number
    detectionCount: number
    correctionCount: number
    mentalHealthCount: number
    feedbackCount: number
    topPhrases: { phrase: string; count: number }[]
    correctionSkill: { promoted: boolean; score: number; trials: number } | null
  } | null>(null)
  const [honestyLoading, setHonestyLoading] = useState(false)
  const [storageStats, setStorageStats] = useState<Record<string, number> | null>(null)
  const [storageLoading, setStorageLoading] = useState(false)
  const [evictionResult, setEvictionResult] = useState<Record<string, number> | null>(null)
  const [evictionRunning, setEvictionRunning] = useState(false)
  const [modelProvider, setModelProvider] = useState("openrouter")
  const [modelName, setModelName] = useState("")
  const [modelSaving, setModelSaving] = useState(false)
  const [modelSaved, setModelSaved] = useState(false)
  const [ollamaModels, setOllamaModels] = useState<string[]>([])

  useEffect(() => {
    const saved = localStorage.getItem("ensemble-personality")
    if (saved && personalities[saved]) {
      setActivePersonality(saved)
    }

    // Load saved descriptions
    const savedDescs: Record<string, string> = {}
    for (const id of Object.keys(personalities)) {
      const desc = localStorage.getItem(`ensemble-desc-${id}`)
      if (desc) savedDescs[id] = desc
    }
    setDescriptions(savedDescs)
  }, [])

  useEffect(() => {
    if (activeTab === "learned") {
      loadSkills()
    }
    if (activeTab === "grows") {
      loadProposals()
    }
    if (activeTab === "honesty") {
      loadHonestyStats()
    }
    if (activeTab === "storage") {
      loadStorageStats()
    }
  }, [activeTab, activePersonality])

  useEffect(() => {
    fetch(`/api/characters/${activePersonality}`)
      .then(r => r.json())
      .then(data => {
        const provider = data.provider ?? "openrouter"
        setModelProvider(provider)
        setModelName(data.llmModel ?? "")
        setModelSaved(false)
        if (provider === "ollama") fetchOllamaModels()
      })
      .catch(() => {})
  }, [activePersonality])

  function fetchOllamaModels() {
    fetch("/api/ollama/models")
      .then(r => r.json())
      .then(data => setOllamaModels(data.models ?? []))
      .catch(() => setOllamaModels([]))
  }

  async function loadSkills() {
    setSkillsLoading(true)
    try {
      const res = await fetch(`/api/skills?character=${activePersonality}`)
      const data = await res.json()
      setSkills(Array.isArray(data) ? data : [])
    } catch {
      setSkills([])
    } finally {
      setSkillsLoading(false)
    }
  }

  async function loadProposals() {
    setProposalsLoading(true)
    try {
      const res = await fetch(`/api/skills/proposals?character=${activePersonality}`)
      const data = await res.json()
      setProposals(Array.isArray(data) ? data : [])
    } catch {
      setProposals([])
    } finally {
      setProposalsLoading(false)
    }
  }

  async function resolveProposal(id: string, accepted: boolean) {
    await fetch(`/api/skills/proposals/${id}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ accepted }),
    })
    await loadProposals()
  }

  async function deleteSkill(name: string) {
    await fetch(`/api/skills?name=${encodeURIComponent(name)}&character=${activePersonality}`, { method: "DELETE" })
    await loadSkills()
  }

  async function resetBehaviors() {
    await fetch("/api/skills", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "reset_behaviors" }),
    })
    setResetConfirm(null)
    await loadSkills()
  }

  async function resetMemory() {
    await fetch("/api/skills", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "reset_memory", characterId: activePersonality }),
    })
    setResetConfirm(null)
  }

  async function factoryReset() {
    await fetch("/api/skills", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "factory_reset" }),
    })
    setResetConfirm(null)
    await loadSkills()
  }

  async function loadHonestyStats() {
    setHonestyLoading(true)
    try {
      const res = await fetch(`/api/honesty?character=${activePersonality}`)
      const data = await res.json()
      setHonestyStats(data)
    } catch {
      setHonestyStats(null)
    } finally {
      setHonestyLoading(false)
    }
  }

  async function loadStorageStats() {
    setStorageLoading(true)
    setEvictionResult(null)
    try {
      const res = await fetch("/api/maintenance")
      const data = await res.json()
      setStorageStats(data)
    } catch {
      setStorageStats(null)
    } finally {
      setStorageLoading(false)
    }
  }

  async function runCleanup() {
    setEvictionRunning(true)
    try {
      const res = await fetch("/api/maintenance", { method: "POST" })
      const result = await res.json()
      setEvictionResult(result)
      await loadStorageStats()
    } catch {
      setEvictionResult(null)
    } finally {
      setEvictionRunning(false)
    }
  }

  function selectPersonality(id: string) {
    setActivePersonality(id)
    localStorage.setItem("ensemble-personality", id)
  }

  function updateDescription(id: string, value: string) {
    setDescriptions(prev => ({ ...prev, [id]: value }))
    if (value.trim()) {
      localStorage.setItem(`ensemble-desc-${id}`, value)
    } else {
      localStorage.removeItem(`ensemble-desc-${id}`)
    }
  }

  async function saveModelConfig() {
    setModelSaving(true)
    setModelSaved(false)
    try {
      await fetch(`/api/characters/${activePersonality}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ provider: modelProvider, llmModel: modelName.trim() || null }),
      })
      setModelSaved(true)
    } finally {
      setModelSaving(false)
    }
  }

  function newChat() {
    localStorage.removeItem("ensemble-session-id")
    window.location.href = "/chat"
  }

  const characterName = personalities[activePersonality].name

  return (
    <div className="flex flex-col h-screen bg-zinc-900">
      <Header />
      <div className="flex flex-1 flex-col items-center gap-8 p-8 overflow-y-auto">
        <h1 className="text-3xl font-bold text-white">Settings</h1>

        {/* Character selector — always visible */}
        <div className="w-full max-w-2xl">
          <h2 className="text-xl font-semibold text-white mb-4">Choose Your AI</h2>
          <div className="flex gap-4">
            {Object.values(personalities).map((p) => (
              <button
                key={p.id}
                onClick={() => selectPersonality(p.id)}
                className={`flex-1 rounded-lg p-6 text-left transition ${
                  activePersonality === p.id
                    ? "bg-blue-600 text-white ring-2 ring-blue-400"
                    : "bg-zinc-800 text-zinc-300 hover:bg-zinc-700"
                }`}
              >
                <div className="text-lg font-bold">{p.name}</div>
                <div className="text-sm mt-2 opacity-80">
                  {p.defaultDescription.split(".")[0]}.
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Tab nav */}
        <div className="w-full max-w-2xl">
          <div className="flex border-b border-zinc-700 mb-6">
            <button
              onClick={() => setActiveTab("personality")}
              className={`px-4 py-2 text-sm font-medium transition ${
                activeTab === "personality"
                  ? "text-white border-b-2 border-blue-500"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              Personality
            </button>
            <button
              onClick={() => setActiveTab("learned")}
              className={`px-4 py-2 text-sm font-medium transition ${
                activeTab === "learned"
                  ? "text-white border-b-2 border-blue-500"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              What {characterName} Has Learned
            </button>
            <button
              onClick={() => setActiveTab("grows")}
              className={`px-4 py-2 text-sm font-medium transition ${
                activeTab === "grows"
                  ? "text-white border-b-2 border-blue-500"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              How {characterName} Grows
            </button>
            <button
              onClick={() => setActiveTab("honesty")}
              className={`px-4 py-2 text-sm font-medium transition ${
                activeTab === "honesty"
                  ? "text-white border-b-2 border-blue-500"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              How {characterName} Pushes Back
            </button>
            <button
              onClick={() => setActiveTab("storage")}
              className={`px-4 py-2 text-sm font-medium transition ${
                activeTab === "storage"
                  ? "text-white border-b-2 border-blue-500"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              Data &amp; Storage
            </button>
          </div>

          {/* ── Personality tab ── */}
          {activeTab === "personality" && (
            <div className="space-y-8">
              <div>
                <h2 className="text-xl font-semibold text-white mb-2">
                  {characterName}&apos;s Personality
                </h2>
                <p className="text-zinc-500 text-sm mb-3">
                  Customize the personality description. Leave blank to use the default.
                </p>
                <textarea
                  value={descriptions[activePersonality] || ""}
                  onChange={(e) => updateDescription(activePersonality, e.target.value)}
                  placeholder={personalities[activePersonality].defaultDescription}
                  rows={4}
                  className="w-full rounded bg-zinc-800 p-3 text-white text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                <p className="text-zinc-600 text-xs mt-1">
                  Base prompt (always active): {personalities[activePersonality].basePrompt}
                </p>
              </div>

              <div>
                <h2 className="text-xl font-semibold text-white mb-2">Model</h2>
                <p className="text-zinc-500 text-sm mb-3">
                  Override which AI provider and model {characterName} uses. Leave model blank to use the provider default.
                </p>
                <div className="flex gap-3 items-end">
                  <div className="flex flex-col gap-1">
                    <label className="text-zinc-400 text-xs">Provider</label>
                    <select
                      value={modelProvider}
                      onChange={e => {
                        const p = e.target.value
                        setModelProvider(p)
                        setModelSaved(false)
                        setModelName("")
                        if (p === "ollama") fetchOllamaModels()
                      }}
                      className="rounded bg-zinc-800 px-3 py-2 text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="openrouter">OpenRouter</option>
                      <option value="gemini">Gemini</option>
                      <option value="ollama">Ollama (local)</option>
                    </select>
                  </div>
                  <div className="flex flex-col gap-1 flex-1">
                    <label className="text-zinc-400 text-xs">Model name (optional)</label>
                    {modelProvider === "ollama" && ollamaModels.length > 0 ? (
                      <select
                        value={modelName}
                        onChange={e => { setModelName(e.target.value); setModelSaved(false) }}
                        className="rounded bg-zinc-800 px-3 py-2 text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                      >
                        <option value="">— provider default —</option>
                        {ollamaModels.map(m => (
                          <option key={m} value={m}>{m}</option>
                        ))}
                      </select>
                    ) : (
                      <input
                        type="text"
                        value={modelName}
                        onChange={e => { setModelName(e.target.value); setModelSaved(false) }}
                        placeholder={modelProvider === "ollama" ? "loading models..." : "e.g. anthropic/claude-opus-4-6"}
                        className="rounded bg-zinc-800 px-3 py-2 text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    )}
                  </div>
                  <button
                    onClick={saveModelConfig}
                    disabled={modelSaving}
                    className="rounded bg-blue-700 px-4 py-2 text-white text-sm hover:bg-blue-600 disabled:opacity-50 transition whitespace-nowrap"
                  >
                    {modelSaving ? "Saving…" : modelSaved ? "Saved" : "Save"}
                  </button>
                </div>
                {/* Layer 2: Provider sycophancy tier guidance */}
                {(() => {
                  const tier = classifyTier(modelProvider, modelName)
                  const warning = tierWarning(tier)
                  return (
                    <div className="mt-3 rounded border border-zinc-700 bg-zinc-800/50 px-3 py-2 text-xs text-zinc-400">
                      <span className="font-semibold text-zinc-300">Honesty tiers: </span>
                      <span className="text-emerald-400">Low sycophancy</span> — Claude, DeepSeek-V3, Qwen2.5 &nbsp;·&nbsp;
                      <span className="text-yellow-400">Moderate</span> — Gemini 2.5 Pro, GPT-4o &nbsp;·&nbsp;
                      <span className="text-red-400">Higher risk</span> — Llama 3.x family.
                      {warning && (
                        <p className={`mt-1 font-medium ${tier.tier === "high" ? "text-red-400" : "text-yellow-400"}`}>
                          {warning}
                        </p>
                      )}
                    </div>
                  )
                })()}
              </div>

              <div>
                <h2 className="text-xl font-semibold text-white mb-4">Conversation</h2>
                <button
                  onClick={newChat}
                  className="rounded bg-zinc-700 px-4 py-2 text-white hover:bg-zinc-600"
                >
                  Start New Chat
                </button>
                <p className="text-zinc-500 text-sm mt-2">
                  Clears the current conversation and starts fresh. Previous chats are saved.
                </p>
              </div>
            </div>
          )}

          {/* ── What [Name] Has Learned tab ── */}
          {activeTab === "learned" && (
            <div className="space-y-6">
              <p className="text-zinc-400 text-sm">
                These are behavioral guidelines {characterName} has
                developed over time. Promoted skills are actively used in every conversation.
              </p>

              {skillsLoading ? (
                <p className="text-zinc-500 text-sm">Loading...</p>
              ) : skills.length === 0 ? (
                <p className="text-zinc-500 text-sm">
                  No skills yet. {characterName} will develop these over time.
                </p>
              ) : (
                <div className="space-y-2">
                  {skills.map(skill => (
                    <div
                      key={skill.id}
                      className="flex items-center justify-between bg-zinc-800 rounded-lg px-4 py-3"
                    >
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-white text-sm font-medium">{skill.skillName}</span>
                          {skill.promoted && (
                            <span className="text-xs bg-blue-600 text-white px-1.5 py-0.5 rounded">active</span>
                          )}
                          {skill.protected && (
                            <span className="text-xs bg-zinc-600 text-zinc-300 px-1.5 py-0.5 rounded">protected</span>
                          )}
                          {skill.autoGenerated && (
                            <span className="text-xs bg-green-800 text-green-300 px-1.5 py-0.5 rounded">auto</span>
                          )}
                        </div>
                        <div className="text-zinc-500 text-xs mt-0.5">
                          Score: {Math.round(skill.score * 100)}% · {skill.trials} trials
                          {skill.lastFired && ` · last used ${new Date(skill.lastFired).toLocaleDateString()}`}
                        </div>
                      </div>
                      {!skill.protected && (
                        <button
                          onClick={() => deleteSkill(skill.skillName)}
                          className="ml-4 text-zinc-500 hover:text-red-400 text-sm transition"
                          title="Remove this skill"
                        >
                          ✕
                        </button>
                      )}
                    </div>
                  ))}
                </div>
              )}

              {/* Reset options */}
              <div className="border-t border-zinc-700 pt-6 space-y-3">
                <h3 className="text-sm font-semibold text-zinc-400 uppercase tracking-wide">Reset</h3>
                {resetConfirm ? (
                  <div className="bg-zinc-800 rounded-lg p-4 space-y-3">
                    <p className="text-white text-sm">{resetConfirm === "behaviors"
                      ? "Reset all learned behaviors? This cannot be undone."
                      : resetConfirm === "memory"
                      ? `Clear ${characterName}'s topic memory? This cannot be undone.`
                      : "Factory reset everything — all memory, skills, and conversation history? This cannot be undone."
                    }</p>
                    <div className="flex gap-3">
                      <button
                        onClick={() => {
                          if (resetConfirm === "behaviors") resetBehaviors()
                          else if (resetConfirm === "memory") resetMemory()
                          else factoryReset()
                        }}
                        className="rounded bg-red-700 px-4 py-2 text-white text-sm hover:bg-red-600"
                      >
                        Confirm
                      </button>
                      <button
                        onClick={() => setResetConfirm(null)}
                        className="rounded bg-zinc-700 px-4 py-2 text-white text-sm hover:bg-zinc-600"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-wrap gap-3">
                    <button
                      onClick={() => setResetConfirm("behaviors")}
                      className="rounded bg-zinc-700 px-4 py-2 text-zinc-300 text-sm hover:bg-zinc-600"
                    >
                      Reset learned behaviors
                    </button>
                    <button
                      onClick={() => setResetConfirm("memory")}
                      className="rounded bg-zinc-700 px-4 py-2 text-zinc-300 text-sm hover:bg-zinc-600"
                    >
                      Clear {characterName}&apos;s memory
                    </button>
                    <button
                      onClick={() => setResetConfirm("factory")}
                      className="rounded bg-red-900 px-4 py-2 text-red-300 text-sm hover:bg-red-800"
                    >
                      Factory reset
                    </button>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* ── How [Name] Pushes Back tab ── */}
          {activeTab === "honesty" && (
            <div className="space-y-6">
              <p className="text-zinc-400 text-sm">
                {characterName} uses a layered defense system to stay honest. Here&apos;s what&apos;s
                active and what&apos;s been detected in your recent conversations.
              </p>

              {/* Defense layers summary */}
              <div className="rounded-lg bg-zinc-800 p-5 space-y-3">
                <h3 className="text-white text-sm font-semibold">Active Defense Layers</h3>
                <div className="space-y-2 text-xs text-zinc-400">
                  <div className="flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">✓</span>
                    <span><span className="text-zinc-300">System prompt</span> — every response includes explicit anti-sycophancy directives</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">✓</span>
                    <span><span className="text-zinc-300">Output filter</span> — responses are scanned for flattering phrases before delivery</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">✓</span>
                    <span><span className="text-zinc-300">Adversarial context</span> — when you make a claim, {characterName} retrieves contradicting information too</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">✓</span>
                    <span><span className="text-zinc-300">Hard constraints</span> — long responses must contain at least one counter-consideration</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">✓</span>
                    <span><span className="text-zinc-300">Adaptive reward</span> — sycophancy detections penalize {characterName}&apos;s behavioral score over time</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">✓</span>
                    <span><span className="text-zinc-300">Mental health guardrails</span> — {characterName} redirects to professional resources if needed, not therapeutic intervention</span>
                  </div>
                </div>
              </div>

              {/* Stats from recent sessions */}
              {honestyLoading ? (
                <p className="text-zinc-500 text-sm">Loading...</p>
              ) : honestyStats ? (
                <div className="space-y-4">
                  <h3 className="text-white text-sm font-semibold">
                    Last {honestyStats.sessionCount} Sessions
                  </h3>
                  <div className="grid grid-cols-4 gap-3">
                    <div className="rounded-lg bg-zinc-800 px-4 py-3 text-center">
                      <div className={`text-2xl font-bold ${honestyStats.detectionCount > 0 ? "text-yellow-400" : "text-emerald-400"}`}>
                        {honestyStats.detectionCount}
                      </div>
                      <div className="text-zinc-500 text-xs mt-0.5">Too agreeable</div>
                    </div>
                    <div className="rounded-lg bg-zinc-800 px-4 py-3 text-center">
                      <div className={`text-2xl font-bold ${honestyStats.correctionCount > 0 ? "text-orange-400" : "text-emerald-400"}`}>
                        {honestyStats.correctionCount}
                      </div>
                      <div className="text-zinc-500 text-xs mt-0.5">You corrected {characterName}</div>
                    </div>
                    <div className="rounded-lg bg-zinc-800 px-4 py-3 text-center">
                      <div className={`text-2xl font-bold ${honestyStats.feedbackCount > 0 ? "text-yellow-400" : "text-emerald-400"}`}>
                        {honestyStats.feedbackCount}
                      </div>
                      <div className="text-zinc-500 text-xs mt-0.5">You called it out</div>
                    </div>
                    <div className="rounded-lg bg-zinc-800 px-4 py-3 text-center">
                      <div className="text-2xl font-bold text-zinc-300">
                        {honestyStats.mentalHealthCount}
                      </div>
                      <div className="text-zinc-500 text-xs mt-0.5">Safety redirects</div>
                    </div>
                  </div>

                  {honestyStats.topPhrases.length > 0 && (
                    <div className="rounded-lg bg-zinc-800 p-4">
                      <h4 className="text-zinc-400 text-xs uppercase tracking-wide mb-2">Caught saying</h4>
                      <div className="space-y-1">
                        {honestyStats.topPhrases.map(({ phrase, count }) => (
                          <div key={phrase} className="flex justify-between text-xs">
                            <span className="text-zinc-300 font-mono">&ldquo;{phrase}&rdquo;</span>
                            <span className="text-zinc-500">{count}×</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {honestyStats.correctionSkill && (
                    <div className="rounded-lg border border-emerald-800 bg-zinc-800 p-4">
                      <h4 className="text-emerald-400 text-xs uppercase tracking-wide mb-1">Correction skill active</h4>
                      <p className="text-zinc-400 text-xs">
                        {characterName} has generated a behavioral guideline for handling pushback directly.
                        {honestyStats.correctionSkill.promoted
                          ? " It is promoted and active in all conversations."
                          : ` In trial (${honestyStats.correctionSkill.trials} trials, score ${honestyStats.correctionSkill.score}%).`}
                      </p>
                    </div>
                  )}

                  {honestyStats.detectionCount === 0 && honestyStats.correctionCount === 0 && (
                    <p className="text-zinc-500 text-sm">
                      No issues detected in recent conversations. The system is working.
                    </p>
                  )}
                </div>
              ) : (
                <p className="text-zinc-500 text-sm">Could not load honesty stats.</p>
              )}
            </div>
          )}

          {/* ── Data & Storage tab ── */}
          {activeTab === "storage" && (
            <div className="space-y-6">
              <p className="text-zinc-400 text-sm">
                Storage statistics and cleanup controls. Old spans and summaries are safe to prune —
                they&apos;re observability data, not conversations.
              </p>

              {storageLoading ? (
                <p className="text-zinc-500 text-sm">Loading...</p>
              ) : storageStats ? (
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { label: "Topics", key: "topics" },
                    { label: "Sessions", key: "sessions" },
                    { label: "Messages", key: "messages" },
                    { label: "Spans", key: "spans" },
                    { label: "Skills", key: "skills" },
                    { label: "Summaries", key: "summaries" },
                  ].map(({ label, key }) => (
                    <div key={key} className="rounded-lg bg-zinc-800 px-4 py-3 text-center">
                      <div className="text-2xl font-bold text-white">{storageStats[key] ?? 0}</div>
                      <div className="text-zinc-500 text-xs mt-0.5">{label}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-zinc-500 text-sm">Could not load storage stats.</p>
              )}

              <div className="space-y-3">
                <p className="text-zinc-500 text-xs">
                  Cleanup removes spans older than 30 days, conversation summaries older than 90 days,
                  and sessions beyond the 100 most recent. Conversations and topic memory are not affected.
                </p>
                <button
                  onClick={runCleanup}
                  disabled={evictionRunning}
                  className="rounded bg-zinc-700 px-4 py-2 text-zinc-300 text-sm hover:bg-zinc-600 disabled:opacity-50 disabled:cursor-not-allowed transition"
                >
                  {evictionRunning ? "Running cleanup..." : "Run cleanup"}
                </button>

                {evictionResult && (
                  <div className="rounded-lg bg-zinc-800 px-4 py-3 text-sm space-y-1">
                    <p className="text-zinc-300 font-medium">Cleanup complete</p>
                    <p className="text-zinc-500">Spans removed: {evictionResult.spansDeleted}</p>
                    <p className="text-zinc-500">Sessions removed: {evictionResult.sessionsDeleted}</p>
                    <p className="text-zinc-500">Summaries removed: {evictionResult.summariesDeleted}</p>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* ── How [Name] Grows tab ── */}
          {activeTab === "grows" && (
            <div className="space-y-6">
              <p className="text-zinc-400 text-sm">
                {characterName} can improve how they respond to you over time. These are proposed
                updates — review them and decide whether to apply each one.
              </p>

              {proposalsLoading ? (
                <p className="text-zinc-500 text-sm">Loading...</p>
              ) : proposals.length === 0 ? (
                <div className="rounded-lg bg-zinc-800 px-6 py-8 text-center">
                  <p className="text-zinc-400 text-sm">No pending proposals.</p>
                  <p className="text-zinc-600 text-xs mt-2">
                    {characterName} will suggest improvements here as your conversations grow.
                  </p>
                </div>
              ) : (
                <div className="space-y-4">
                  {proposals.map(proposal => (
                    <div key={proposal.id} className="rounded-lg bg-zinc-800 p-5 space-y-4">
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <div className="text-white text-sm font-medium">{proposal.skillName}</div>
                          <div className="text-zinc-500 text-xs mt-0.5">{proposal.reason}</div>
                        </div>
                        <div className="text-zinc-600 text-xs whitespace-nowrap">
                          auto-accepts {new Date(proposal.autoAcceptAt).toLocaleDateString()}
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <div className="text-zinc-500 text-xs mb-1 uppercase tracking-wide">Before</div>
                          <div className="rounded bg-zinc-900 px-3 py-2 text-zinc-400 text-xs font-mono whitespace-pre-wrap">
                            {proposal.oldBody}
                          </div>
                        </div>
                        <div>
                          <div className="text-zinc-500 text-xs mb-1 uppercase tracking-wide">After</div>
                          <div className="rounded bg-zinc-900 px-3 py-2 text-green-400 text-xs font-mono whitespace-pre-wrap">
                            {proposal.newBody}
                          </div>
                        </div>
                      </div>

                      <div className="flex gap-3">
                        <button
                          onClick={() => resolveProposal(proposal.id, true)}
                          className="rounded bg-blue-700 px-4 py-1.5 text-white text-sm hover:bg-blue-600 transition"
                        >
                          Apply
                        </button>
                        <button
                          onClick={() => resolveProposal(proposal.id, false)}
                          className="rounded bg-zinc-700 px-4 py-1.5 text-zinc-300 text-sm hover:bg-zinc-600 transition"
                        >
                          Dismiss
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
