-- CreateTable
CREATE TABLE "Topic" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'concept',
    "summary" TEXT NOT NULL,
    "characterId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Topic_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TopicMessage" (
    "topicId" TEXT NOT NULL,
    "messageId" TEXT NOT NULL,

    CONSTRAINT "TopicMessage_pkey" PRIMARY KEY ("topicId","messageId")
);

-- CreateTable
CREATE TABLE "Span" (
    "id" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "traceId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ok',
    "durationMs" INTEGER,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Span_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SkillStat" (
    "id" TEXT NOT NULL,
    "skillName" TEXT NOT NULL,
    "characterId" TEXT NOT NULL DEFAULT 'aimee',
    "score" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "trials" INTEGER NOT NULL DEFAULT 0,
    "lastFired" TIMESTAMP(3),
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "protected" BOOLEAN NOT NULL DEFAULT false,
    "promoted" BOOLEAN NOT NULL DEFAULT false,
    "staleAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SkillStat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ApoVariant" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slot" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "score" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "trials" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT false,
    "parentId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ApoVariant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SkillProposal" (
    "id" TEXT NOT NULL,
    "skillName" TEXT NOT NULL,
    "characterId" TEXT NOT NULL,
    "oldBody" TEXT NOT NULL,
    "newBody" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "accepted" BOOLEAN,
    "autoAcceptAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SkillProposal_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ConversationSummary" (
    "id" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "characterId" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "turnStart" INTEGER NOT NULL,
    "turnEnd" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ConversationSummary_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CharacterConfig" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "basePrompt" TEXT NOT NULL,
    "model" TEXT NOT NULL DEFAULT '/Aimee.glb',
    "voiceLocal" TEXT NOT NULL DEFAULT 'Aimee.mp3',
    "voiceCloud" TEXT,
    "description" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CharacterConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Topic_name_key" ON "Topic"("name");

-- CreateIndex
CREATE INDEX "Span_sessionId_idx" ON "Span"("sessionId");

-- CreateIndex
CREATE INDEX "Span_kind_idx" ON "Span"("kind");

-- CreateIndex
CREATE INDEX "SkillStat_characterId_idx" ON "SkillStat"("characterId");

-- CreateIndex
CREATE UNIQUE INDEX "SkillStat_skillName_characterId_key" ON "SkillStat"("skillName", "characterId");

-- CreateIndex
CREATE INDEX "ApoVariant_slot_active_idx" ON "ApoVariant"("slot", "active");

-- CreateIndex
CREATE UNIQUE INDEX "ApoVariant_name_slot_key" ON "ApoVariant"("name", "slot");

-- CreateIndex
CREATE INDEX "SkillProposal_characterId_accepted_idx" ON "SkillProposal"("characterId", "accepted");

-- CreateIndex
CREATE INDEX "ConversationSummary_sessionId_characterId_idx" ON "ConversationSummary"("sessionId", "characterId");

-- CreateIndex
CREATE UNIQUE INDEX "CharacterConfig_name_key" ON "CharacterConfig"("name");

-- AddForeignKey
ALTER TABLE "TopicMessage" ADD CONSTRAINT "TopicMessage_topicId_fkey" FOREIGN KEY ("topicId") REFERENCES "Topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TopicMessage" ADD CONSTRAINT "TopicMessage_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "Message"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Span" ADD CONSTRAINT "Span_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConversationSummary" ADD CONSTRAINT "ConversationSummary_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
